routes/web.php
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('user-alerts/read', 'UserAlertsController@read');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Product Categories
    Route::delete('product-categories/destroy', 'ProductCategoryController@massDestroy')->name('product-categories.massDestroy');
    Route::post('product-categories/media', 'ProductCategoryController@storeMedia')->name('product-categories.storeMedia');
    Route::post('product-categories/ckmedia', 'ProductCategoryController@storeCKEditorImages')->name('product-categories.storeCKEditorImages');
    Route::resource('product-categories', 'ProductCategoryController');

    // Product Tags
    Route::delete('product-tags/destroy', 'ProductTagController@massDestroy')->name('product-tags.massDestroy');
    Route::resource('product-tags', 'ProductTagController');

    // Products
    Route::delete('products/destroy', 'ProductController@massDestroy')->name('products.massDestroy');
    Route::post('products/media', 'ProductController@storeMedia')->name('products.storeMedia');
    Route::post('products/ckmedia', 'ProductController@storeCKEditorImages')->name('products.storeCKEditorImages');
    Route::resource('products', 'ProductController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Content Categories
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tags
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Pages
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
    Route::resource('content-pages', 'ContentPageController');

    // Menus
    Route::delete('menus/destroy', 'MenuController@massDestroy')->name('menus.massDestroy');
    Route::resource('menus', 'MenuController');

    // Orders
    Route::delete('orders/destroy', 'OrderController@massDestroy')->name('orders.massDestroy');
    Route::resource('orders', 'OrderController', ['except' => ['create', 'store']]);

    // Carts
    Route::delete('carts/destroy', 'CartController@massDestroy')->name('carts.massDestroy');
    Route::resource('carts', 'CartController', ['except' => ['create', 'store']]);

    // Types
    Route::delete('types/destroy', 'TypeController@massDestroy')->name('types.massDestroy');
    Route::resource('types', 'TypeController');

    // Attributes
    Route::delete('attributes/destroy', 'AttributeController@massDestroy')->name('attributes.massDestroy');
    Route::resource('attributes', 'AttributeController');

    // Languages
    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
    Route::post('languages/media', 'LanguageController@storeMedia')->name('languages.storeMedia');
    Route::post('languages/ckmedia', 'LanguageController@storeCKEditorImages')->name('languages.storeCKEditorImages');
    Route::resource('languages', 'LanguageController');

    // Product Languages
    Route::delete('product-languages/destroy', 'ProductLanguageController@massDestroy')->name('product-languages.massDestroy');
    Route::post('product-languages/media', 'ProductLanguageController@storeMedia')->name('product-languages.storeMedia');
    Route::post('product-languages/ckmedia', 'ProductLanguageController@storeCKEditorImages')->name('product-languages.storeCKEditorImages');
    Route::resource('product-languages', 'ProductLanguageController');

    // Sale Offers
    Route::delete('sale-offers/destroy', 'SaleOffersController@massDestroy')->name('sale-offers.massDestroy');
    Route::resource('sale-offers', 'SaleOffersController');

    // Taxes
    Route::delete('taxes/destroy', 'TaxController@massDestroy')->name('taxes.massDestroy');
    Route::resource('taxes', 'TaxController');

    // Product Seos
    Route::delete('product-seos/destroy', 'ProductSeoController@massDestroy')->name('product-seos.massDestroy');
    Route::resource('product-seos', 'ProductSeoController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/media', 'TicketController@storeMedia')->name('tickets.storeMedia');
    Route::post('tickets/ckmedia', 'TicketController@storeCKEditorImages')->name('tickets.storeCKEditorImages');
    Route::resource('tickets', 'TicketController');

    // Ticket Messages
    Route::delete('ticket-messages/destroy', 'TicketMessageController@massDestroy')->name('ticket-messages.massDestroy');
    Route::post('ticket-messages/media', 'TicketMessageController@storeMedia')->name('ticket-messages.storeMedia');
    Route::post('ticket-messages/ckmedia', 'TicketMessageController@storeCKEditorImages')->name('ticket-messages.storeCKEditorImages');
    Route::resource('ticket-messages', 'TicketMessageController');

    // Ratings
    Route::delete('ratings/destroy', 'RatingController@massDestroy')->name('ratings.massDestroy');
    Route::resource('ratings', 'RatingController');

    // Shipments
    Route::delete('shipments/destroy', 'ShipmentController@massDestroy')->name('shipments.massDestroy');
    Route::post('shipments/media', 'ShipmentController@storeMedia')->name('shipments.storeMedia');
    Route::post('shipments/ckmedia', 'ShipmentController@storeCKEditorImages')->name('shipments.storeCKEditorImages');
    Route::resource('shipments', 'ShipmentController');

    // Payment Gateways
    Route::delete('payment-gateways/destroy', 'PaymentGatewayController@massDestroy')->name('payment-gateways.massDestroy');
    Route::resource('payment-gateways', 'PaymentGatewayController');

    // Payment Transactions
    Route::delete('payment-transactions/destroy', 'PaymentTransactionController@massDestroy')->name('payment-transactions.massDestroy');
    Route::resource('payment-transactions', 'PaymentTransactionController');

    // Refunds
    Route::delete('refunds/destroy', 'RefundController@massDestroy')->name('refunds.massDestroy');
    Route::resource('refunds', 'RefundController');

    // Settings
    Route::delete('settings/destroy', 'SettingController@massDestroy')->name('settings.massDestroy');
    Route::post('settings/media', 'SettingController@storeMedia')->name('settings.storeMedia');
    Route::post('settings/ckmedia', 'SettingController@storeCKEditorImages')->name('settings.storeCKEditorImages');
    Route::resource('settings', 'SettingController');

    // Vouchers
    Route::delete('vouchers/destroy', 'VoucherController@massDestroy')->name('vouchers.massDestroy');
    Route::resource('vouchers', 'VoucherController');

    // Wishlists
    Route::delete('wishlists/destroy', 'WishlistController@massDestroy')->name('wishlists.massDestroy');
    Route::resource('wishlists', 'WishlistController');

    // Stores
    Route::delete('stores/destroy', 'StoreController@massDestroy')->name('stores.massDestroy');
    Route::post('stores/media', 'StoreController@storeMedia')->name('stores.storeMedia');
    Route::post('stores/ckmedia', 'StoreController@storeCKEditorImages')->name('stores.storeCKEditorImages');
    Route::resource('stores', 'StoreController');

    // Approvals
    Route::delete('approvals/destroy', 'ApprovalController@massDestroy')->name('approvals.massDestroy');
    Route::resource('approvals', 'ApprovalController');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');

app/Voucher.php
<?php

namespace App;

use App\Traits\Auditable;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Voucher extends Model
{
    use SoftDeletes, Auditable;

    public $table = 'vouchers';

    public static $searchable = [
        'title',
    ];

    protected $dates = [
        'expired_at',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'title',
        'category_id',
        'percentage',
        'expired_at',
        'max_usage',
        'store_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function category()
    {
        return $this->belongsTo(ProductCategory::class, 'category_id');
    }

    public function getExpiredAtAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setExpiredAtAttribute($value)
    {
        $this->attributes['expired_at'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }

    public function store()
    {
        return $this->belongsTo(Store::class, 'store_id');
    }
}

app/Http/Controllers/Admin/VoucherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyVoucherRequest;
use App\Http\Requests\StoreVoucherRequest;
use App\Http\Requests\UpdateVoucherRequest;
use App\ProductCategory;
use App\Store;
use App\Voucher;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class VoucherController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('voucher_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $vouchers = Voucher::all();

        return view('admin.vouchers.index', compact('vouchers'));
    }

    public function create()
    {
        abort_if(Gate::denies('voucher_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categories = ProductCategory::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $stores = Store::all()->pluck('title', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.vouchers.create', compact('categories', 'stores'));
    }

    public function store(StoreVoucherRequest $request)
    {
        $voucher = Voucher::create($request->all());

        return redirect()->route('admin.vouchers.index');
    }

    public function edit(Voucher $voucher)
    {
        abort_if(Gate::denies('voucher_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $categories = ProductCategory::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $stores = Store::all()->pluck('title', 'id')->prepend(trans('global.pleaseSelect'), '');

        $voucher->load('category', 'store');

        return view('admin.vouchers.edit', compact('categories', 'stores', 'voucher'));
    }

    public function update(UpdateVoucherRequest $request, Voucher $voucher)
    {
        $voucher->update($request->all());

        return redirect()->route('admin.vouchers.index');
    }

    public function show(Voucher $voucher)
    {
        abort_if(Gate::denies('voucher_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $voucher->load('category', 'store');

        return view('admin.vouchers.show', compact('voucher'));
    }

    public function destroy(Voucher $voucher)
    {
        abort_if(Gate::denies('voucher_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $voucher->delete();

        return back();
    }

    public function massDestroy(MassDestroyVoucherRequest $request)
    {
        Voucher::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/vouchers/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.voucher.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.vouchers.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">{{ trans('cruds.voucher.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', '') }}">
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="category_id">{{ trans('cruds.voucher.fields.category') }}</label>
                <select class="form-control select2 {{ $errors->has('category') ? 'is-invalid' : '' }}" name="category_id" id="category_id">
                    @foreach($categories as $id => $category)
                        <option value="{{ $id }}" {{ old('category_id') == $id ? 'selected' : '' }}>{{ $category }}</option>
                    @endforeach
                </select>
                @if($errors->has('category'))
                    <span class="text-danger">{{ $errors->first('category') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.category_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="percentage">{{ trans('cruds.voucher.fields.percentage') }}</label>
                <input class="form-control {{ $errors->has('percentage') ? 'is-invalid' : '' }}" type="text" name="percentage" id="percentage" value="{{ old('percentage', '') }}">
                @if($errors->has('percentage'))
                    <span class="text-danger">{{ $errors->first('percentage') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.percentage_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="expired_at">{{ trans('cruds.voucher.fields.expired_at') }}</label>
                <input class="form-control date {{ $errors->has('expired_at') ? 'is-invalid' : '' }}" type="text" name="expired_at" id="expired_at" value="{{ old('expired_at') }}">
                @if($errors->has('expired_at'))
                    <span class="text-danger">{{ $errors->first('expired_at') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.expired_at_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="max_usage">{{ trans('cruds.voucher.fields.max_usage') }}</label>
                <input class="form-control {{ $errors->has('max_usage') ? 'is-invalid' : '' }}" type="text" name="max_usage" id="max_usage" value="{{ old('max_usage', '') }}">
                @if($errors->has('max_usage'))
                    <span class="text-danger">{{ $errors->first('max_usage') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.max_usage_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="store_id">{{ trans('cruds.voucher.fields.store') }}</label>
                <select class="form-control select2 {{ $errors->has('store') ? 'is-invalid' : '' }}" name="store_id" id="store_id">
                    @foreach($stores as $id => $store)
                        <option value="{{ $id }}" {{ old('store_id') == $id ? 'selected' : '' }}>{{ $store }}</option>
                    @endforeach
                </select>
                @if($errors->has('store'))
                    <span class="text-danger">{{ $errors->first('store') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.store_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/vouchers/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.voucher.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.vouchers.update", [$voucher->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="title">{{ trans('cruds.voucher.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', $voucher->title) }}">
                @if($errors->has('title'))
                    <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="category_id">{{ trans('cruds.voucher.fields.category') }}</label>
                <select class="form-control select2 {{ $errors->has('category') ? 'is-invalid' : '' }}" name="category_id" id="category_id">
                    @foreach($categories as $id => $category)
                        <option value="{{ $id }}" {{ ($voucher->category ? $voucher->category->id : old('category_id')) == $id ? 'selected' : '' }}>{{ $category }}</option>
                    @endforeach
                </select>
                @if($errors->has('category'))
                    <span class="text-danger">{{ $errors->first('category') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.category_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="percentage">{{ trans('cruds.voucher.fields.percentage') }}</label>
                <input class="form-control {{ $errors->has('percentage') ? 'is-invalid' : '' }}" type="text" name="percentage" id="percentage" value="{{ old('percentage', $voucher->percentage) }}">
                @if($errors->has('percentage'))
                    <span class="text-danger">{{ $errors->first('percentage') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.percentage_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="expired_at">{{ trans('cruds.voucher.fields.expired_at') }}</label>
                <input class="form-control date {{ $errors->has('expired_at') ? 'is-invalid' : '' }}" type="text" name="expired_at" id="expired_at" value="{{ old('expired_at', $voucher->expired_at) }}">
                @if($errors->has('expired_at'))
                    <span class="text-danger">{{ $errors->first('expired_at') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.expired_at_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="max_usage">{{ trans('cruds.voucher.fields.max_usage') }}</label>
                <input class="form-control {{ $errors->has('max_usage') ? 'is-invalid' : '' }}" type="text" name="max_usage" id="max_usage" value="{{ old('max_usage', $voucher->max_usage) }}">
                @if($errors->has('max_usage'))
                    <span class="text-danger">{{ $errors->first('max_usage') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.max_usage_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="store_id">{{ trans('cruds.voucher.fields.store') }}</label>
                <select class="form-control select2 {{ $errors->has('store') ? 'is-invalid' : '' }}" name="store_id" id="store_id">
                    @foreach($stores as $id => $store)
                        <option value="{{ $id }}" {{ ($voucher->store ? $voucher->store->id : old('store_id')) == $id ? 'selected' : '' }}>{{ $store }}</option>
                    @endforeach
                </select>
                @if($errors->has('store'))
                    <span class="text-danger">{{ $errors->first('store') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.voucher.fields.store_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/vouchers/index.blade.php
@extends('layouts.admin')
@section('content')
@can('voucher_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.vouchers.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.voucher.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.voucher.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Voucher">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.voucher.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.voucher.fields.title') }}
                        </th>
                        <th>
                            {{ trans('cruds.voucher.fields.category') }}
                        </th>
                        <th>
                            {{ trans('cruds.voucher.fields.percentage') }}
                        </th>
                        <th>
                            {{ trans('cruds.voucher.fields.expired_at') }}
                        </th>
                        <th>
                            {{ trans('cruds.voucher.fields.max_usage') }}
                        </th>
                        <th>
                            {{ trans('cruds.voucher.fields.store') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($vouchers as $key => $voucher)
                        <tr data-entry-id="{{ $voucher->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $voucher->id ?? '' }}
                            </td>
                            <td>
                                {{ $voucher->title ?? '' }}
                            </td>
                            <td>
                                {{ $voucher->category->name ?? '' }}
                            </td>
                            <td>
                                {{ $voucher->percentage ?? '' }}
                            </td>
                            <td>
                                {{ $voucher->expired_at ?? '' }}
                            </td>
                            <td>
                                {{ $voucher->max_usage ?? '' }}
                            </td>
                            <td>
                                {{ $voucher->store->title ?? '' }}
                            </td>
                            <td>
                                @can('voucher_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.vouchers.show', $voucher->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('voucher_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.vouchers.edit', $voucher->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('voucher_delete')
                                    <form action="{{ route('admin.vouchers.destroy', $voucher->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('voucher_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.vouchers.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Voucher:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection